name: hodmc
version: 0.0.1
author: skippi
main: io.github.skippi.hodmc.HodMC
website: https://github.com/skippi/hodmc
api-version: 1.16
commands:
  hod:
    description: hodmc porcelain command
    usage: /<command> [subcommand]
