/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.skippi.hodmc;

import org.bukkit.plugin.java.JavaPlugin;

public class HodMC extends JavaPlugin {
    public boolean someLibraryMethod() {
        return true;
    }

    @Override
    public void onEnable() {
        System.out.println("hello world");
    }
}
